// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPYFtRa5MeMr2pKxBC4dFsdmuJBiGRgHI',
    appId: '1:415570387622:web:692bca0433bc7dc6a18a67',
    messagingSenderId: '415570387622',
    projectId: 'spot-saver-seven-bd485',
    authDomain: 'spot-saver-seven-bd485.firebaseapp.com',
    storageBucket: 'spot-saver-seven-bd485.firebasestorage.app',
    measurementId: 'G-EYD85FMSFX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFnnkYGx9C-ME4ByRn_73tOoeFoqRkHpY',
    appId: '1:415570387622:android:0be6bdd99a57d93ca18a67',
    messagingSenderId: '415570387622',
    projectId: 'spot-saver-seven-bd485',
    storageBucket: 'spot-saver-seven-bd485.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs2WpJc5Htc3ytzjD5CB7_bZ4tcAj--3c',
    appId: '1:415570387622:ios:500d2ad391bb74b4a18a67',
    messagingSenderId: '415570387622',
    projectId: 'spot-saver-seven-bd485',
    storageBucket: 'spot-saver-seven-bd485.firebasestorage.app',
    iosBundleId: 'com.example.spotSaver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBs2WpJc5Htc3ytzjD5CB7_bZ4tcAj--3c',
    appId: '1:415570387622:ios:500d2ad391bb74b4a18a67',
    messagingSenderId: '415570387622',
    projectId: 'spot-saver-seven-bd485',
    storageBucket: 'spot-saver-seven-bd485.firebasestorage.app',
    iosBundleId: 'com.example.spotSaver',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPYFtRa5MeMr2pKxBC4dFsdmuJBiGRgHI',
    appId: '1:415570387622:web:0be70f778736939ba18a67',
    messagingSenderId: '415570387622',
    projectId: 'spot-saver-seven-bd485',
    authDomain: 'spot-saver-seven-bd485.firebaseapp.com',
    storageBucket: 'spot-saver-seven-bd485.firebasestorage.app',
    measurementId: 'G-Q2NHY1BCF5',
  );
}
